# Generated by Django 4.1 on 2022-09-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ect_project_repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=6)),
                ('first_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=15)),
                ('othername', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('phone_number', models.CharField(max_length=11)),
                ('project_topic', models.CharField(max_length=70)),
                ('department', models.CharField(max_length=3)),
                ('supervisor', models.CharField(max_length=30)),
                ('year_of_sub', models.CharField(max_length=4)),
                ('accession_no', models.CharField(max_length=6)),
                ('shell_no', models.IntegerField()),
                ('row_no', models.IntegerField()),
                ('copies', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
